server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_product?currentSchema=sc_product&ssl=false
    username: nurlandev
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    user:
      name: nurlan
      password: nurlan123



